name: Creating the documentation with Maven

on:              # Ce workflow se déclenche sur un pull request fusionnée (merged)
  pull_request:
    types:
      - closed

jobs:      
Documentation : # Nom du job : Documentation
  name: Documentation
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest # OS où s'exécute le job
  steps:
   - uses: actions/checkout@v4 
   - uses: actions/setup-java@v4
     with:
      distribution: 'corretto'
      java-version: '21'
   - name: java
     run: mvn -B javadoc::javadoc
   - uses: peaceiris/actions-gh-pages@v4  
     with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      publish_dir: ./target/reports/apidocs
